Repository SovereignCloudStack/calendar, pull requests merged in 2024-04, with the labels that each got.

#265 Add IaaS IPv4 Breakout session to the calendar
  teams/iaas/onetimes.yml
Labels: SCS-VP10

#275 Add breakout on IAM hackathon - team alignment.
  teams/iam_n_sec/onetimes.yml
Labels: housekeeping, IAM

#279 Feat/enable missing entries
  .github/workflows/yaml2ics.yml
  lightning_talks.yml
  main.yml
Labels: housekeeping
